name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node and Install Dependencies
        uses: ./.github/workflows/actions/setup
        with:
          node-version: '20'

      - name: Build Docker Image
        run: |
          docker build -t bookstore-api .
          docker images bookstore-api
        shell: bash

  push-to-dockerhub:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push Docker Image to Docker Hub
        run: |
          docker tag bookstore-api ${{ secrets.DOCKERHUB_USERNAME }}/bookstore-api:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bookstore-api:latest
